GET http://localhost:3001/user

###

POST http://localhost:3001/user
Content-Type: application/json

{
    "name": "Cottrez",
    "surname": "Rémy",
    "email": "remycottrez@gmail.com",
    "password": "test",
    "description": "description test"
}

###

POST http://localhost:3001/admin/login
Content-Type: application/json

{
    "email": "remycottrez@gmail.com",
    "password": "test"
}

### 

POST http://localhost:3001/user/update
Content-Type: application/json

{
    "email": "remycottrez@gmail.com",
    "name": "CottrezTest"
}

###

GET http://localhost:3001/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicmVteWNvdHRyZXpAZ21haWwuY29tIiwiaWF0IjoxNjY1MDQ1NDkwfQ.gU4mGfNULu9HpnALxWp07pyxz44jZuML5rEYjQ_boaA